---
- name: First playbook
  hosts: 
    - debian
  gather_facts: no

  vars:
    bg_image_dest: "{{ansible_user_dir}}/Picures/bg.jpg"
    servers:
      - galaxy
      - vulcan
      - ameros        

  tasks:
    - name: Install base packages
      become: yes
      apt:
        name: 
          - htop
          - vim
          - kazam 
          - filezilla
          - bluefish
        update_cache: yes    
        state: present
      tags:
        - packages
 
    - name: downloand bg image
      get_url:
        url: https://cdn.wallpapersafari.com/55/73/ghY4rc.jpg
        dest: /home/ubuntu/Pictures/bg.jpg
      tags:
        - backgroung
    - name: change bg image
      shell: "gsettings set org.gnome.desktop.background picture-uri file://{{bg_image_dest}}"
      tags:
        - background 
            
